### ISSUE TITLE
Release 1.18.2?

### ISSUE THREAD

**Issue by wolfv** [conda-forge/krb5-feedstock#24]
The 1.18.x seems to be out since February. https://web.mit.edu/kerberos/krb5-1.18/

Does this require a migration?

**Comment by mariusvniekerk** [comment]
According to https://abi-laboratory.pro/?view=timeline&l=krb5 it very much does incompatible things so would require a migration for the 1.18 series

**Comment by chrisburr** [comment]
A migration for 1.19 was added in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1496
