### ISSUE TITLE
Python 2.7 is failing on OS X

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/krb5-feedstock#8]
See https://travis-ci.org/conda-forge/krb5-feedstock/jobs/361358504

xref #7

**Comment by jakirkham** [comment]
Error seemed to have disappeared in the [merge commit build]( https://travis-ci.org/conda-forge/krb5-feedstock/jobs/361733550 ) for that PR. Also has been passing since. Maybe it was a fluke?
